#	Calvin Aduma
#	CPSC 111-Section 003
#	Lab 9
# 	This program creates a makefile for the function created in the
#	part a of lab 9.

lab9: driver.c highest.c initialize.c innerProduct.c
	gcc -Wall -o lab9 driver.c highest.c initialize.c innerProduct.c

run: lab9
	./lab9

clean:
	rm lab9
